name: 'Chromatic Deployment'

on:
  push:
  pull_request:

jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Chromatic and capture output
        id: chromatic
        run: |
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} > chromatic_output.txt
          echo "CHROMATIC_URL=$(grep -o 'https://www.chromatic.com/build[^ ]*' chromatic_output.txt)" >> $GITHUB_OUTPUT

      - name: Comment on PR with update time and Storybook URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = '${{ steps.chromatic.outputs.CHROMATIC_URL }}';

            const now = new Date();
            const kstOffset = 9 * 60; // KST offset in minutes
            const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
            const kst = new Date(utc + (kstOffset * 60000));

            const pad = (n) => n.toString().padStart(2, '0');
            const formattedDate = `${kst.getFullYear()}ë…„ ${pad(kst.getMonth() + 1)}ì›” ${pad(kst.getDate())}ì¼ ${pad(kst.getHours())}ì‹œ ${pad(kst.getMinutes())}ë¶„ ${pad(kst.getSeconds())}ì´ˆ`;

            const body = `Update: ${formattedDate}\nStorybook ë¯¸ë¦¬ë³´ê¸° ğŸ¨ : ${url}`;


            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
